"""Index list actions."""

from .actions import (
    ApplyIlmPolicy,
    CloseIndices,
    Cold2FrozenIndices,
    ConfirmIlmPhase,
    CreateIndices,
    DeleteDataStreams,
    DeleteIndices,
    ForceMerge,
    OpenIndices,
    PromoteIlm,
    PutIndexSettings,
    ReindexIndices,
    RolloverDataStreams,
    RolloverIndices,
    SetAllocation,
    SetReplicas,
    ShrinkIndices,
    UpdateAliases,
)

__all__ = [
    "ApplyIlmPolicy",
    "CloseIndices",
    "Cold2FrozenIndices",
    "ConfirmIlmPhase",
    "CreateIndices",
    "DeleteDataStreams",
    "DeleteIndices",
    "ForceMerge",
    "OpenIndices",
    "PromoteIlm",
    "PutIndexSettings",
    "ReindexIndices",
    "RolloverDataStreams",
    "RolloverIndices",
    "SetAllocation",
    "SetReplicas",
    "ShrinkIndices",
    "UpdateAliases",
]
